version: '3'
services:

  common_db:
    image: postgres:11.7
    restart: always
    environment:
      - POSTGRES_USER=ppri
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=mnf
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    network_mode: bridge


volumes:
  postgres-data:
