// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.2.0
// source: api/mnf/v1/mnf.proto

package mnf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Part struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MnfId      string `protobuf:"bytes,2,opt,name=mnf_id,json=mnfId,proto3" json:"mnf_id,omitempty"`
	VendorCode string `protobuf:"bytes,3,opt,name=vendor_code,json=vendorCode,proto3" json:"vendor_code,omitempty"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: sql:"type:timestamptz"
	DeletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Part) Reset() {
	*x = Part{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Part) GetMnfId() string {
	if x != nil {
		return x.MnfId
	}
	return ""
}

func (x *Part) GetVendorCode() string {
	if x != nil {
		return x.VendorCode
	}
	return ""
}

func (x *Part) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetDeletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreatePartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Part `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreatePartRequest) Reset() {
	*x = CreatePartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartRequest) ProtoMessage() {}

func (x *CreatePartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartRequest.ProtoReflect.Descriptor instead.
func (*CreatePartRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePartRequest) GetItem() *Part {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreatePartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatePartResponse) Reset() {
	*x = CreatePartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartResponse) ProtoMessage() {}

func (x *CreatePartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartResponse.ProtoReflect.Descriptor instead.
func (*CreatePartResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePartResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePartsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Part `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreatePartsRequest) Reset() {
	*x = CreatePartsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartsRequest) ProtoMessage() {}

func (x *CreatePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartsRequest.ProtoReflect.Descriptor instead.
func (*CreatePartsRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePartsRequest) GetItems() []*Part {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePartsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *CreatePartsResponse) Reset() {
	*x = CreatePartsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartsResponse) ProtoMessage() {}

func (x *CreatePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartsResponse.ProtoReflect.Descriptor instead.
func (*CreatePartsResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePartsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetPartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{5}
}

func (x *GetPartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Part `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetPartResponse) Reset() {
	*x = GetPartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponse) ProtoMessage() {}

func (x *GetPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponse.ProtoReflect.Descriptor instead.
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{6}
}

func (x *GetPartResponse) GetItem() *Part {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListPartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mnfid string `protobuf:"bytes,1,opt,name=mnfid,proto3" json:"mnfid,omitempty"`
}

func (x *ListPartRequest) Reset() {
	*x = ListPartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartRequest) ProtoMessage() {}

func (x *ListPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartRequest.ProtoReflect.Descriptor instead.
func (*ListPartRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{7}
}

func (x *ListPartRequest) GetMnfid() string {
	if x != nil {
		return x.Mnfid
	}
	return ""
}

type ListPartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Part `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListPartResponse) Reset() {
	*x = ListPartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartResponse) ProtoMessage() {}

func (x *ListPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartResponse.ProtoReflect.Descriptor instead.
func (*ListPartResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{8}
}

func (x *ListPartResponse) GetItems() []*Part {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeletePartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePartRequest) Reset() {
	*x = DeletePartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartRequest) ProtoMessage() {}

func (x *DeletePartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartRequest.ProtoReflect.Descriptor instead.
func (*DeletePartRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ststus string `protobuf:"bytes,1,opt,name=ststus,proto3" json:"ststus,omitempty"`
}

func (x *DeletePartResponse) Reset() {
	*x = DeletePartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartResponse) ProtoMessage() {}

func (x *DeletePartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartResponse.ProtoReflect.Descriptor instead.
func (*DeletePartResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePartResponse) GetStstus() string {
	if x != nil {
		return x.Ststus
	}
	return ""
}

type UpdatePartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Part `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *UpdatePartRequest) Reset() {
	*x = UpdatePartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartRequest) ProtoMessage() {}

func (x *UpdatePartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePartRequest) GetItem() *Part {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdatePartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdatePartResponse) Reset() {
	*x = UpdatePartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartResponse) ProtoMessage() {}

func (x *UpdatePartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePartResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdatePartsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Part `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UpdatePartsRequest) Reset() {
	*x = UpdatePartsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartsRequest) ProtoMessage() {}

func (x *UpdatePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartsRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePartsRequest) GetItems() []*Part {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdatePartsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdatePartsResponse) Reset() {
	*x = UpdatePartsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartsResponse) ProtoMessage() {}

func (x *UpdatePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartsResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePartsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Mnf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @inject_tag: sql:"type:timestamptz,default:now()"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Mnf) Reset() {
	*x = Mnf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mnf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mnf) ProtoMessage() {}

func (x *Mnf) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mnf.ProtoReflect.Descriptor instead.
func (*Mnf) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{15}
}

func (x *Mnf) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mnf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mnf) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateMnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Mnf `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateMnfRequest) Reset() {
	*x = CreateMnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMnfRequest) ProtoMessage() {}

func (x *CreateMnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMnfRequest.ProtoReflect.Descriptor instead.
func (*CreateMnfRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMnfRequest) GetItem() *Mnf {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateMnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateMnfResponse) Reset() {
	*x = CreateMnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMnfResponse) ProtoMessage() {}

func (x *CreateMnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMnfResponse.ProtoReflect.Descriptor instead.
func (*CreateMnfResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{17}
}

func (x *CreateMnfResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateMnfsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Mnf `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CreateMnfsRequest) Reset() {
	*x = CreateMnfsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMnfsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMnfsRequest) ProtoMessage() {}

func (x *CreateMnfsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMnfsRequest.ProtoReflect.Descriptor instead.
func (*CreateMnfsRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{18}
}

func (x *CreateMnfsRequest) GetItems() []*Mnf {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateMnfsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *CreateMnfsResponse) Reset() {
	*x = CreateMnfsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMnfsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMnfsResponse) ProtoMessage() {}

func (x *CreateMnfsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMnfsResponse.ProtoReflect.Descriptor instead.
func (*CreateMnfsResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{19}
}

func (x *CreateMnfsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetMnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMnfRequest) Reset() {
	*x = GetMnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMnfRequest) ProtoMessage() {}

func (x *GetMnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMnfRequest.ProtoReflect.Descriptor instead.
func (*GetMnfRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{20}
}

func (x *GetMnfRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Mnf `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetMnfResponse) Reset() {
	*x = GetMnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMnfResponse) ProtoMessage() {}

func (x *GetMnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMnfResponse.ProtoReflect.Descriptor instead.
func (*GetMnfResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{21}
}

func (x *GetMnfResponse) GetItem() *Mnf {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListMnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListMnfRequest) Reset() {
	*x = ListMnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMnfRequest) ProtoMessage() {}

func (x *ListMnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMnfRequest.ProtoReflect.Descriptor instead.
func (*ListMnfRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{22}
}

func (x *ListMnfRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Mnf `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListMnfResponse) Reset() {
	*x = ListMnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMnfResponse) ProtoMessage() {}

func (x *ListMnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMnfResponse.ProtoReflect.Descriptor instead.
func (*ListMnfResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{23}
}

func (x *ListMnfResponse) GetItems() []*Mnf {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteMnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMnfRequest) Reset() {
	*x = DeleteMnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMnfRequest) ProtoMessage() {}

func (x *DeleteMnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMnfRequest.ProtoReflect.Descriptor instead.
func (*DeleteMnfRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteMnfRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ststus string `protobuf:"bytes,1,opt,name=ststus,proto3" json:"ststus,omitempty"`
}

func (x *DeleteMnfResponse) Reset() {
	*x = DeleteMnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMnfResponse) ProtoMessage() {}

func (x *DeleteMnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMnfResponse.ProtoReflect.Descriptor instead.
func (*DeleteMnfResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteMnfResponse) GetStstus() string {
	if x != nil {
		return x.Ststus
	}
	return ""
}

type UpdateMnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Mnf `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *UpdateMnfRequest) Reset() {
	*x = UpdateMnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMnfRequest) ProtoMessage() {}

func (x *UpdateMnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMnfRequest.ProtoReflect.Descriptor instead.
func (*UpdateMnfRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateMnfRequest) GetItem() *Mnf {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateMnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateMnfResponse) Reset() {
	*x = UpdateMnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMnfResponse) ProtoMessage() {}

func (x *UpdateMnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMnfResponse.ProtoReflect.Descriptor instead.
func (*UpdateMnfResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateMnfResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateMnfsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Mnf `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UpdateMnfsRequest) Reset() {
	*x = UpdateMnfsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMnfsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMnfsRequest) ProtoMessage() {}

func (x *UpdateMnfsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMnfsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMnfsRequest) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateMnfsRequest) GetItems() []*Mnf {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateMnfsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateMnfsResponse) Reset() {
	*x = UpdateMnfsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mnf_v1_mnf_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMnfsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMnfsResponse) ProtoMessage() {}

func (x *UpdateMnfsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_mnf_v1_mnf_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMnfsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMnfsResponse) Descriptor() ([]byte, []int) {
	return file_api_mnf_v1_mnf_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateMnfsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_mnf_v1_mnf_proto protoreflect.FileDescriptor

var file_api_mnf_v1_mnf_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6e, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01,
	0x0a, 0x04, 0x50, 0x61, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x6e, 0x66, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6e, 0x66, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x35, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x74, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x24, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x38, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x27, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x64, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x74, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x27, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6e, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x6e, 0x66, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x23, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2c, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x73, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x73, 0x74, 0x75, 0x73, 0x22,
	0x35, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x2c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x6e, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2d,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x64, 0x0a,
	0x03, 0x4d, 0x6e, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x33, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x6e, 0x66, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x23, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6e, 0x66, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x26, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x6e, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x1f, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6e, 0x66, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x26, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x34, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6e,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6e, 0x66, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6e, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x73, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x73, 0x74, 0x75, 0x73,
	0x22, 0x33, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6e, 0x66, 0x52,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x2b, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x36, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6e, 0x66, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2c, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x93, 0x05, 0x0a, 0x0b, 0x50, 0x61, 0x72,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x12, 0x19, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x3a,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x60, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x2f,
	0x62, 0x75, 0x6c, 0x6b, 0x3a, 0x01, 0x2a, 0x12, 0x51, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x74, 0x12, 0x16, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x6e, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x61, 0x72, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x57, 0x0a, 0x08, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x17, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x12, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x2f, 0x7b, 0x6d, 0x6e, 0x66,
	0x69, 0x64, 0x7d, 0x12, 0x5a, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x12, 0x19, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d,
	0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x2a, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12,
	0x5b, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x12, 0x19, 0x2e,
	0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x1a, 0x08, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x3a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x60, 0x0a, 0x0b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x6d, 0x6e,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x1a, 0x0d, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x3a, 0x01, 0x2a, 0x32, 0xed,
	0x04, 0x0a, 0x0a, 0x4d, 0x6e, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x12, 0x18, 0x2e, 0x6d, 0x6e, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x07, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66,
	0x3a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x5b, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x6e, 0x66, 0x73, 0x12, 0x19, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x6e, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x10, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66, 0x2f, 0x61, 0x72, 0x72,
	0x3a, 0x01, 0x2a, 0x12, 0x4d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x6e, 0x66, 0x12, 0x15, 0x2e,
	0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x4b, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6e, 0x66, 0x12, 0x16, 0x2e,
	0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66, 0x12,
	0x56, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x12, 0x18, 0x2e, 0x6d,
	0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x2a, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x6e, 0x66, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x57, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4d, 0x6e, 0x66, 0x12, 0x18, 0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x1a, 0x07, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66, 0x3a, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x12, 0x5c, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x73, 0x12, 0x19,
	0x2e, 0x6d, 0x6e, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e,
	0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x6e, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6e, 0x66, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x1a, 0x0c, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x6e, 0x66, 0x2f, 0x62, 0x75, 0x6c, 0x6b, 0x3a, 0x01, 0x2a, 0x42, 0x10,
	0x5a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6e, 0x66, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x6e, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mnf_v1_mnf_proto_rawDescOnce sync.Once
	file_api_mnf_v1_mnf_proto_rawDescData = file_api_mnf_v1_mnf_proto_rawDesc
)

func file_api_mnf_v1_mnf_proto_rawDescGZIP() []byte {
	file_api_mnf_v1_mnf_proto_rawDescOnce.Do(func() {
		file_api_mnf_v1_mnf_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mnf_v1_mnf_proto_rawDescData)
	})
	return file_api_mnf_v1_mnf_proto_rawDescData
}

var file_api_mnf_v1_mnf_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_mnf_v1_mnf_proto_goTypes = []interface{}{
	(*Part)(nil),                // 0: mnf.v1.Part
	(*CreatePartRequest)(nil),   // 1: mnf.v1.CreatePartRequest
	(*CreatePartResponse)(nil),  // 2: mnf.v1.CreatePartResponse
	(*CreatePartsRequest)(nil),  // 3: mnf.v1.CreatePartsRequest
	(*CreatePartsResponse)(nil), // 4: mnf.v1.CreatePartsResponse
	(*GetPartRequest)(nil),      // 5: mnf.v1.GetPartRequest
	(*GetPartResponse)(nil),     // 6: mnf.v1.GetPartResponse
	(*ListPartRequest)(nil),     // 7: mnf.v1.ListPartRequest
	(*ListPartResponse)(nil),    // 8: mnf.v1.ListPartResponse
	(*DeletePartRequest)(nil),   // 9: mnf.v1.DeletePartRequest
	(*DeletePartResponse)(nil),  // 10: mnf.v1.DeletePartResponse
	(*UpdatePartRequest)(nil),   // 11: mnf.v1.UpdatePartRequest
	(*UpdatePartResponse)(nil),  // 12: mnf.v1.UpdatePartResponse
	(*UpdatePartsRequest)(nil),  // 13: mnf.v1.UpdatePartsRequest
	(*UpdatePartsResponse)(nil), // 14: mnf.v1.UpdatePartsResponse
	(*Mnf)(nil),                 // 15: mnf.v1.Mnf
	(*CreateMnfRequest)(nil),    // 16: mnf.v1.CreateMnfRequest
	(*CreateMnfResponse)(nil),   // 17: mnf.v1.CreateMnfResponse
	(*CreateMnfsRequest)(nil),   // 18: mnf.v1.CreateMnfsRequest
	(*CreateMnfsResponse)(nil),  // 19: mnf.v1.CreateMnfsResponse
	(*GetMnfRequest)(nil),       // 20: mnf.v1.GetMnfRequest
	(*GetMnfResponse)(nil),      // 21: mnf.v1.GetMnfResponse
	(*ListMnfRequest)(nil),      // 22: mnf.v1.ListMnfRequest
	(*ListMnfResponse)(nil),     // 23: mnf.v1.ListMnfResponse
	(*DeleteMnfRequest)(nil),    // 24: mnf.v1.DeleteMnfRequest
	(*DeleteMnfResponse)(nil),   // 25: mnf.v1.DeleteMnfResponse
	(*UpdateMnfRequest)(nil),    // 26: mnf.v1.UpdateMnfRequest
	(*UpdateMnfResponse)(nil),   // 27: mnf.v1.UpdateMnfResponse
	(*UpdateMnfsRequest)(nil),   // 28: mnf.v1.UpdateMnfsRequest
	(*UpdateMnfsResponse)(nil),  // 29: mnf.v1.UpdateMnfsResponse
	(*timestamp.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_api_mnf_v1_mnf_proto_depIdxs = []int32{
	30, // 0: mnf.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	30, // 1: mnf.v1.Part.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 2: mnf.v1.CreatePartRequest.item:type_name -> mnf.v1.Part
	0,  // 3: mnf.v1.CreatePartsRequest.items:type_name -> mnf.v1.Part
	0,  // 4: mnf.v1.GetPartResponse.item:type_name -> mnf.v1.Part
	0,  // 5: mnf.v1.ListPartResponse.items:type_name -> mnf.v1.Part
	0,  // 6: mnf.v1.UpdatePartRequest.item:type_name -> mnf.v1.Part
	0,  // 7: mnf.v1.UpdatePartsRequest.items:type_name -> mnf.v1.Part
	30, // 8: mnf.v1.Mnf.created_at:type_name -> google.protobuf.Timestamp
	15, // 9: mnf.v1.CreateMnfRequest.item:type_name -> mnf.v1.Mnf
	15, // 10: mnf.v1.CreateMnfsRequest.items:type_name -> mnf.v1.Mnf
	15, // 11: mnf.v1.GetMnfResponse.item:type_name -> mnf.v1.Mnf
	15, // 12: mnf.v1.ListMnfResponse.items:type_name -> mnf.v1.Mnf
	15, // 13: mnf.v1.UpdateMnfRequest.item:type_name -> mnf.v1.Mnf
	15, // 14: mnf.v1.UpdateMnfsRequest.items:type_name -> mnf.v1.Mnf
	1,  // 15: mnf.v1.PartService.CreatePart:input_type -> mnf.v1.CreatePartRequest
	3,  // 16: mnf.v1.PartService.CreateParts:input_type -> mnf.v1.CreatePartsRequest
	5,  // 17: mnf.v1.PartService.GetPart:input_type -> mnf.v1.GetPartRequest
	7,  // 18: mnf.v1.PartService.ListPart:input_type -> mnf.v1.ListPartRequest
	9,  // 19: mnf.v1.PartService.DeletePart:input_type -> mnf.v1.DeletePartRequest
	11, // 20: mnf.v1.PartService.UpdatePart:input_type -> mnf.v1.UpdatePartRequest
	13, // 21: mnf.v1.PartService.UpdateParts:input_type -> mnf.v1.UpdatePartsRequest
	16, // 22: mnf.v1.MnfService.CreateMnf:input_type -> mnf.v1.CreateMnfRequest
	18, // 23: mnf.v1.MnfService.CreateMnfs:input_type -> mnf.v1.CreateMnfsRequest
	20, // 24: mnf.v1.MnfService.GetMnf:input_type -> mnf.v1.GetMnfRequest
	22, // 25: mnf.v1.MnfService.ListMnf:input_type -> mnf.v1.ListMnfRequest
	24, // 26: mnf.v1.MnfService.DeleteMnf:input_type -> mnf.v1.DeleteMnfRequest
	26, // 27: mnf.v1.MnfService.UpdateMnf:input_type -> mnf.v1.UpdateMnfRequest
	28, // 28: mnf.v1.MnfService.UpdateMnfs:input_type -> mnf.v1.UpdateMnfsRequest
	2,  // 29: mnf.v1.PartService.CreatePart:output_type -> mnf.v1.CreatePartResponse
	4,  // 30: mnf.v1.PartService.CreateParts:output_type -> mnf.v1.CreatePartsResponse
	6,  // 31: mnf.v1.PartService.GetPart:output_type -> mnf.v1.GetPartResponse
	8,  // 32: mnf.v1.PartService.ListPart:output_type -> mnf.v1.ListPartResponse
	10, // 33: mnf.v1.PartService.DeletePart:output_type -> mnf.v1.DeletePartResponse
	12, // 34: mnf.v1.PartService.UpdatePart:output_type -> mnf.v1.UpdatePartResponse
	14, // 35: mnf.v1.PartService.UpdateParts:output_type -> mnf.v1.UpdatePartsResponse
	17, // 36: mnf.v1.MnfService.CreateMnf:output_type -> mnf.v1.CreateMnfResponse
	19, // 37: mnf.v1.MnfService.CreateMnfs:output_type -> mnf.v1.CreateMnfsResponse
	21, // 38: mnf.v1.MnfService.GetMnf:output_type -> mnf.v1.GetMnfResponse
	23, // 39: mnf.v1.MnfService.ListMnf:output_type -> mnf.v1.ListMnfResponse
	25, // 40: mnf.v1.MnfService.DeleteMnf:output_type -> mnf.v1.DeleteMnfResponse
	27, // 41: mnf.v1.MnfService.UpdateMnf:output_type -> mnf.v1.UpdateMnfResponse
	29, // 42: mnf.v1.MnfService.UpdateMnfs:output_type -> mnf.v1.UpdateMnfsResponse
	29, // [29:43] is the sub-list for method output_type
	15, // [15:29] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_mnf_v1_mnf_proto_init() }
func file_api_mnf_v1_mnf_proto_init() {
	if File_api_mnf_v1_mnf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mnf_v1_mnf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Part); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePartsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePartsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePartsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mnf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMnfsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMnfsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMnfsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mnf_v1_mnf_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMnfsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mnf_v1_mnf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_mnf_v1_mnf_proto_goTypes,
		DependencyIndexes: file_api_mnf_v1_mnf_proto_depIdxs,
		MessageInfos:      file_api_mnf_v1_mnf_proto_msgTypes,
	}.Build()
	File_api_mnf_v1_mnf_proto = out.File
	file_api_mnf_v1_mnf_proto_rawDesc = nil
	file_api_mnf_v1_mnf_proto_goTypes = nil
	file_api_mnf_v1_mnf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PartServiceClient is the client API for PartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PartServiceClient interface {
	CreatePart(ctx context.Context, in *CreatePartRequest, opts ...grpc.CallOption) (*CreatePartResponse, error)
	CreateParts(ctx context.Context, in *CreatePartsRequest, opts ...grpc.CallOption) (*CreatePartsResponse, error)
	GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error)
	ListPart(ctx context.Context, in *ListPartRequest, opts ...grpc.CallOption) (*ListPartResponse, error)
	DeletePart(ctx context.Context, in *DeletePartRequest, opts ...grpc.CallOption) (*DeletePartResponse, error)
	UpdatePart(ctx context.Context, in *UpdatePartRequest, opts ...grpc.CallOption) (*UpdatePartResponse, error)
	UpdateParts(ctx context.Context, in *UpdatePartsRequest, opts ...grpc.CallOption) (*UpdatePartsResponse, error)
}

type partServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartServiceClient(cc grpc.ClientConnInterface) PartServiceClient {
	return &partServiceClient{cc}
}

func (c *partServiceClient) CreatePart(ctx context.Context, in *CreatePartRequest, opts ...grpc.CallOption) (*CreatePartResponse, error) {
	out := new(CreatePartResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/CreatePart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) CreateParts(ctx context.Context, in *CreatePartsRequest, opts ...grpc.CallOption) (*CreatePartsResponse, error) {
	out := new(CreatePartsResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/CreateParts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) GetPart(ctx context.Context, in *GetPartRequest, opts ...grpc.CallOption) (*GetPartResponse, error) {
	out := new(GetPartResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/GetPart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) ListPart(ctx context.Context, in *ListPartRequest, opts ...grpc.CallOption) (*ListPartResponse, error) {
	out := new(ListPartResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/ListPart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) DeletePart(ctx context.Context, in *DeletePartRequest, opts ...grpc.CallOption) (*DeletePartResponse, error) {
	out := new(DeletePartResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/DeletePart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) UpdatePart(ctx context.Context, in *UpdatePartRequest, opts ...grpc.CallOption) (*UpdatePartResponse, error) {
	out := new(UpdatePartResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/UpdatePart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) UpdateParts(ctx context.Context, in *UpdatePartsRequest, opts ...grpc.CallOption) (*UpdatePartsResponse, error) {
	out := new(UpdatePartsResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.PartService/UpdateParts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartServiceServer is the server API for PartService service.
type PartServiceServer interface {
	CreatePart(context.Context, *CreatePartRequest) (*CreatePartResponse, error)
	CreateParts(context.Context, *CreatePartsRequest) (*CreatePartsResponse, error)
	GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error)
	ListPart(context.Context, *ListPartRequest) (*ListPartResponse, error)
	DeletePart(context.Context, *DeletePartRequest) (*DeletePartResponse, error)
	UpdatePart(context.Context, *UpdatePartRequest) (*UpdatePartResponse, error)
	UpdateParts(context.Context, *UpdatePartsRequest) (*UpdatePartsResponse, error)
}

// UnimplementedPartServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPartServiceServer struct {
}

func (*UnimplementedPartServiceServer) CreatePart(context.Context, *CreatePartRequest) (*CreatePartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePart not implemented")
}
func (*UnimplementedPartServiceServer) CreateParts(context.Context, *CreatePartsRequest) (*CreatePartsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateParts not implemented")
}
func (*UnimplementedPartServiceServer) GetPart(context.Context, *GetPartRequest) (*GetPartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPart not implemented")
}
func (*UnimplementedPartServiceServer) ListPart(context.Context, *ListPartRequest) (*ListPartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPart not implemented")
}
func (*UnimplementedPartServiceServer) DeletePart(context.Context, *DeletePartRequest) (*DeletePartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePart not implemented")
}
func (*UnimplementedPartServiceServer) UpdatePart(context.Context, *UpdatePartRequest) (*UpdatePartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePart not implemented")
}
func (*UnimplementedPartServiceServer) UpdateParts(context.Context, *UpdatePartsRequest) (*UpdatePartsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParts not implemented")
}

func RegisterPartServiceServer(s *grpc.Server, srv PartServiceServer) {
	s.RegisterService(&_PartService_serviceDesc, srv)
}

func _PartService_CreatePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).CreatePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/CreatePart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).CreatePart(ctx, req.(*CreatePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_CreateParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).CreateParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/CreateParts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).CreateParts(ctx, req.(*CreatePartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_GetPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).GetPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/GetPart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).GetPart(ctx, req.(*GetPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_ListPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).ListPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/ListPart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).ListPart(ctx, req.(*ListPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_DeletePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).DeletePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/DeletePart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).DeletePart(ctx, req.(*DeletePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_UpdatePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).UpdatePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/UpdatePart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).UpdatePart(ctx, req.(*UpdatePartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_UpdateParts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePartsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).UpdateParts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.PartService/UpdateParts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).UpdateParts(ctx, req.(*UpdatePartsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mnf.v1.PartService",
	HandlerType: (*PartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePart",
			Handler:    _PartService_CreatePart_Handler,
		},
		{
			MethodName: "CreateParts",
			Handler:    _PartService_CreateParts_Handler,
		},
		{
			MethodName: "GetPart",
			Handler:    _PartService_GetPart_Handler,
		},
		{
			MethodName: "ListPart",
			Handler:    _PartService_ListPart_Handler,
		},
		{
			MethodName: "DeletePart",
			Handler:    _PartService_DeletePart_Handler,
		},
		{
			MethodName: "UpdatePart",
			Handler:    _PartService_UpdatePart_Handler,
		},
		{
			MethodName: "UpdateParts",
			Handler:    _PartService_UpdateParts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mnf/v1/mnf.proto",
}

// MnfServiceClient is the client API for MnfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MnfServiceClient interface {
	CreateMnf(ctx context.Context, in *CreateMnfRequest, opts ...grpc.CallOption) (*CreateMnfResponse, error)
	CreateMnfs(ctx context.Context, in *CreateMnfsRequest, opts ...grpc.CallOption) (*CreateMnfsResponse, error)
	GetMnf(ctx context.Context, in *GetMnfRequest, opts ...grpc.CallOption) (*GetMnfResponse, error)
	ListMnf(ctx context.Context, in *ListMnfRequest, opts ...grpc.CallOption) (*ListMnfResponse, error)
	DeleteMnf(ctx context.Context, in *DeleteMnfRequest, opts ...grpc.CallOption) (*DeleteMnfResponse, error)
	UpdateMnf(ctx context.Context, in *UpdateMnfRequest, opts ...grpc.CallOption) (*UpdateMnfResponse, error)
	UpdateMnfs(ctx context.Context, in *UpdateMnfsRequest, opts ...grpc.CallOption) (*UpdateMnfsResponse, error)
}

type mnfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMnfServiceClient(cc grpc.ClientConnInterface) MnfServiceClient {
	return &mnfServiceClient{cc}
}

func (c *mnfServiceClient) CreateMnf(ctx context.Context, in *CreateMnfRequest, opts ...grpc.CallOption) (*CreateMnfResponse, error) {
	out := new(CreateMnfResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/CreateMnf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnfServiceClient) CreateMnfs(ctx context.Context, in *CreateMnfsRequest, opts ...grpc.CallOption) (*CreateMnfsResponse, error) {
	out := new(CreateMnfsResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/CreateMnfs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnfServiceClient) GetMnf(ctx context.Context, in *GetMnfRequest, opts ...grpc.CallOption) (*GetMnfResponse, error) {
	out := new(GetMnfResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/GetMnf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnfServiceClient) ListMnf(ctx context.Context, in *ListMnfRequest, opts ...grpc.CallOption) (*ListMnfResponse, error) {
	out := new(ListMnfResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/ListMnf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnfServiceClient) DeleteMnf(ctx context.Context, in *DeleteMnfRequest, opts ...grpc.CallOption) (*DeleteMnfResponse, error) {
	out := new(DeleteMnfResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/DeleteMnf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnfServiceClient) UpdateMnf(ctx context.Context, in *UpdateMnfRequest, opts ...grpc.CallOption) (*UpdateMnfResponse, error) {
	out := new(UpdateMnfResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/UpdateMnf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mnfServiceClient) UpdateMnfs(ctx context.Context, in *UpdateMnfsRequest, opts ...grpc.CallOption) (*UpdateMnfsResponse, error) {
	out := new(UpdateMnfsResponse)
	err := c.cc.Invoke(ctx, "/mnf.v1.MnfService/UpdateMnfs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MnfServiceServer is the server API for MnfService service.
type MnfServiceServer interface {
	CreateMnf(context.Context, *CreateMnfRequest) (*CreateMnfResponse, error)
	CreateMnfs(context.Context, *CreateMnfsRequest) (*CreateMnfsResponse, error)
	GetMnf(context.Context, *GetMnfRequest) (*GetMnfResponse, error)
	ListMnf(context.Context, *ListMnfRequest) (*ListMnfResponse, error)
	DeleteMnf(context.Context, *DeleteMnfRequest) (*DeleteMnfResponse, error)
	UpdateMnf(context.Context, *UpdateMnfRequest) (*UpdateMnfResponse, error)
	UpdateMnfs(context.Context, *UpdateMnfsRequest) (*UpdateMnfsResponse, error)
}

// UnimplementedMnfServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMnfServiceServer struct {
}

func (*UnimplementedMnfServiceServer) CreateMnf(context.Context, *CreateMnfRequest) (*CreateMnfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMnf not implemented")
}
func (*UnimplementedMnfServiceServer) CreateMnfs(context.Context, *CreateMnfsRequest) (*CreateMnfsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMnfs not implemented")
}
func (*UnimplementedMnfServiceServer) GetMnf(context.Context, *GetMnfRequest) (*GetMnfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMnf not implemented")
}
func (*UnimplementedMnfServiceServer) ListMnf(context.Context, *ListMnfRequest) (*ListMnfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMnf not implemented")
}
func (*UnimplementedMnfServiceServer) DeleteMnf(context.Context, *DeleteMnfRequest) (*DeleteMnfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMnf not implemented")
}
func (*UnimplementedMnfServiceServer) UpdateMnf(context.Context, *UpdateMnfRequest) (*UpdateMnfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMnf not implemented")
}
func (*UnimplementedMnfServiceServer) UpdateMnfs(context.Context, *UpdateMnfsRequest) (*UpdateMnfsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMnfs not implemented")
}

func RegisterMnfServiceServer(s *grpc.Server, srv MnfServiceServer) {
	s.RegisterService(&_MnfService_serviceDesc, srv)
}

func _MnfService_CreateMnf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMnfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).CreateMnf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/CreateMnf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).CreateMnf(ctx, req.(*CreateMnfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MnfService_CreateMnfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMnfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).CreateMnfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/CreateMnfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).CreateMnfs(ctx, req.(*CreateMnfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MnfService_GetMnf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMnfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).GetMnf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/GetMnf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).GetMnf(ctx, req.(*GetMnfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MnfService_ListMnf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMnfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).ListMnf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/ListMnf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).ListMnf(ctx, req.(*ListMnfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MnfService_DeleteMnf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMnfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).DeleteMnf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/DeleteMnf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).DeleteMnf(ctx, req.(*DeleteMnfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MnfService_UpdateMnf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMnfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).UpdateMnf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/UpdateMnf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).UpdateMnf(ctx, req.(*UpdateMnfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MnfService_UpdateMnfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMnfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MnfServiceServer).UpdateMnfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mnf.v1.MnfService/UpdateMnfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MnfServiceServer).UpdateMnfs(ctx, req.(*UpdateMnfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MnfService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mnf.v1.MnfService",
	HandlerType: (*MnfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMnf",
			Handler:    _MnfService_CreateMnf_Handler,
		},
		{
			MethodName: "CreateMnfs",
			Handler:    _MnfService_CreateMnfs_Handler,
		},
		{
			MethodName: "GetMnf",
			Handler:    _MnfService_GetMnf_Handler,
		},
		{
			MethodName: "ListMnf",
			Handler:    _MnfService_ListMnf_Handler,
		},
		{
			MethodName: "DeleteMnf",
			Handler:    _MnfService_DeleteMnf_Handler,
		},
		{
			MethodName: "UpdateMnf",
			Handler:    _MnfService_UpdateMnf_Handler,
		},
		{
			MethodName: "UpdateMnfs",
			Handler:    _MnfService_UpdateMnfs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mnf/v1/mnf.proto",
}
